### PR TITLE
Added W16_Lab5.md file

### PR DESCRIPTION
**Pull request by alexk2060**
Alexander Kang
Justin Nguyen
5PM Lab

### CODE REVIEW

**Comment by JNguyen96** [comment]
Fixes issue #2 , issue #4 , and issue #11

**Comment by JNguyen96** [comment]
Fixes issue #9

**Comment by JNguyen96** [comment]
Fixes issue #8

**Comment by alexk2060** [comment]
Fixes issue #12

**Comment by JNguyen96** [comment]
Added more test cases for issue #12

**Pull request merged**
